version: '3.0'

expectations:
  population_size: 1000

actions:
         
  generate_study_population_1:
     run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01 to 2020-07-01 by month" --output-format csv.gz
     outputs:
       highly_sensitive:
         cohort: output/input_*.csv.gz

  generate_study_population_2:
     run: cohortextractor:latest generate_cohort --study-definition study_definition_levothyroxine --index-date-range "2020-03-01 to 2020-07-01 by month" --output-format csv.gz
     outputs:
       highly_sensitive:
         cohort: output/input_levo*.csv.gz
       
  generate_study_population_ethnicity:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

  join_cohorts:
    run: >
      cohort-joiner:v0.0.41
        --lhs output/input_20*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population_1, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_20*.csv.gz
                  
  generate_measures:
     run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir output/joined
     needs: [join_cohorts]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_*_rate.csv
         
  generate_measures_levothyroxine:
     run: cohortextractor:latest generate_measures --study-definition study_definition_levothyroxine --skip-existing --output-dir output
     needs: [generate_study_population_2]
     outputs:
       moderately_sensitive:
         measure_csv: output/measure_levo*_rate.csv
         
  generate_practice_deciles_charts:
     run: >
       deciles-charts:v0.0.30
         --input-files output/joined/measure_all_sc_overdue_monitoring_by_practice_rate.csv
         --output-dir output
     needs: [generate_measures]
     outputs:
       moderately_sensitive:
         deciles_charts: output/deciles_*_by_practice_rate.*
              
  generate_plots:
     run: python:latest python analysis/plots.py
     needs: [generate_measures, generate_measures_levothyroxine]
     outputs:
       moderately_sensitive:
         counts: output/joined/plot_*.png
         
  calculate_unique_patients:
    run: python:latest python analysis/calculate_unique_patients.py
    needs: [generate_study_population_1, join_cohorts]
    outputs:
      moderately_sensitive:
        text: output/patient_count.csv
        
  calculate_rate_changes:
     run: python:latest python analysis/calculate_change.py
     needs: [generate_measures]
     outputs:
       moderately_sensitive:
         measure_csv: output/changes_*.csv

  perform_inferential_stats:
    run: r:latest analysis/impact_comparison.R
    needs: [generate_measures]
    outputs: 
      moderately_sensitive:
        results_population: output/analysis/measures_population_ttest.csv
        results_subgroups: output/analysis/measures_subgroup_ttest_heterogeneity.csv
