version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
     run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-01 to 2019-12-01 by month" --output-format=feather
     outputs:
       highly_sensitive:
         cohort: output/input_*.feather
    
  generate_report:
     run: cohort-report:v3.0.0 output/input_2019-09-01.feather output/input_2019-10-01.feather output/input_2019-11-01.feather output/input_2019-12-01.feather
     needs: [generate_study_population_1]
     config:
       output_path: output/cohort_reports_outputs
     outputs:
       moderately_sensitive:
         reports: output/cohort_reports_outputs/descriptives_input_*.html
                  
  generate_measures:
     run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output
     needs: [generate_study_population_1]
     outputs:
       moderately_sensitive:
         measure_csv: output/measure_*_rate.csv

