version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
     run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-02-01 to 2021-02-01 by month" --output-format csv.gz
     outputs:
       highly_sensitive:
         cohort: output/input_*.csv.gz
       
  generate_study_population_ethnicity:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

  join_cohorts:
    run: >
      cohort-joiner:v0.0.7
        --lhs output/input_20*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population_1, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_20*.csv.gz
                  
  generate_measures:
     run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir output/joined
     needs: [join_cohorts]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_*_rate.csv
             
  generate_event_deciles_charts:
     run: >
       deciles-charts:v0.0.21
         --input-files output/joined/measure_all_sc_overdue_monitoring_rate.csv
         --output-dir output/joined
     needs: [generate_measures]
     outputs:
       moderately_sensitive:
         deciles_charts: output/joined/deciles_*_monitoring_rate.*
         
  generate_practice_deciles_charts:
     run: >
       deciles-charts:v0.0.21
         --input-files output/joined/measure_all_sc_overdue_monitoring_by_practice_rate.csv
         --output-dir output/joined
     needs: [generate_measures]
     outputs:
       moderately_sensitive:
         deciles_charts: output/joined/deciles_*_by_practice_rate.*
              
  generate_plots:
     run: python:latest python analysis/plots.py
     needs: [generate_measures]
     outputs:
       moderately_sensitive:
         counts: output/joined/plot_*.png
