version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
        
    
    generate_study_population_2:
        run: cohortextractor generate_cohort --index-date-range "2019-09-01 to 2021-09-01 by month" --output-format=csv.gz
        outputs:
            highly_sensitive:
                cohort: output/input.csv

