version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
     run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-01 to 2021-09-01 by month" --output-format=feather
     outputs:
       highly_sensitive:
         cohort: output/input_*.feather
